server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: COMMANDE-SERVICE
          uri: lb://COMMANDE-SERVICE
          predicates:
            - Path= /commande/**
          filters:
            - RewritePath=/commande/(?<segment>.*), /$\{segment}

        - id: PAIEMENT-SERVICE
          uri: lb://PAIEMENT-SERVICE
          predicates:
            - Path= /paiement/**
          filters:
            - RewritePath=/paiement/(?<segment>.*), /$\{segment}
